### ISSUE TITLE
Authentication degraded v4.1 - unable to check route health and too old resource version

### ISSUE THREAD

**Issue by wilddeuces** [openshift/cluster-authentication-operator#131]
Auth service does not start on fresh installation because following errors:

$ openshift-install version

> ./openshift-install v4.1.0-201905171742-dirty
built from commit 6ba66dbb6c2c53e1901a6d167d1c813bbbf27f4d
release image quay.io/openshift-release-dev/ocp-release@sha256:dc67ad5edd91ca48402309fe0629593e5ae3333435ef8d0bc52c2b62ca725021

$ oc get nodes
> NAME         STATUS    ROLES     AGE       VERSION
os-master1   Ready     master    13h       v1.13.4+27816e1b1
os-master2   Ready     master    13h       v1.13.4+27816e1b1
os-master3   Ready     master    13h       v1.13.4+27816e1b1
os-node1     Ready     worker    13h       v1.13.4+27816e1b1
os-node2     Ready     worker    13h       v1.13.4+27816e1b1
os-node3     Ready     worker    13h       v1.13.4+27816e1b1

$ oc get co

> NAME                                 VERSION      AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                                    Unknown     Unknown       True       12h
cloud-credential                     4.1.0-rc.5   True        False         False      12h
cluster-autoscaler                   4.1.0-rc.5   True        False         False      12h
console                              4.1.0-rc.5   False       True          False      12h
dns                                  4.1.0-rc.5   True        False         False      12h
image-registry                       4.1.0-rc.5   True        False         False      12h
ingress                              4.1.0-rc.5   True        False         False      12h
kube-apiserver                       4.1.0-rc.5   True        False         False      12h
kube-controller-manager              4.1.0-rc.5   True        False         False      12h
kube-scheduler                        4.1.0-rc.5   True        False         False      12h
machine-api                          4.1.0-rc.5   True        False         False      12h
machine-config                       4.1.0-rc.5   True        False         False      12h
marketplace                          4.1.0-rc.5   True        False         False      23m
monitoring                           4.1.0-rc.5   True        False         False      22m
network                              4.1.0-rc.5   True        False         False      12h
node-tuning                          4.1.0-rc.5   True        False         False      12h
openshift-apiserver                  4.1.0-rc.5   True        False         False      12h
openshift-controller-manager         4.1.0-rc.5   True        False         False      12h
openshift-samples                    4.1.0-rc.5   True        False         False      12h
operator-lifecycle-manager           4.1.0-rc.5   True        False         False      12h
operator-lifecycle-manager-catalog   4.1.0-rc.5   True        False         False      12h
service-ca                           4.1.0-rc.5   True        False         False      12h
service-catalog-apiserver            4.1.0-rc.5   True        False         False      12h
service-catalog-controller-manager   4.1.0-rc.5   True        False         False      12h
storage                              4.1.0-rc.5   True        False         False      12h

$ oc get co authentication -oyaml

> apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  creationTimestamp: 2019-06-05T18:16:06Z
  generation: 1
  name: authentication
  resourceVersion: "21493"
  selfLink: /apis/config.openshift.io/v1/clusteroperators/authentication
  uid: fc937d71-87bd-11e9-a2a2-005056ab11e4
spec: {}
status:
  conditions:
  - lastTransitionTime: 2019-06-05T18:17:06Z
    message: 'Degraded: error checking current version: unable to check route health:
      failed to GET route: EOF'
    reason: DegradedOperatorSyncLoopError
    status: "True"
    type: Degraded
  - lastTransitionTime: 2019-06-05T18:16:06Z
    reason: NoData
    status: Unknown
    type: Progressing
  - lastTransitionTime: 2019-06-05T18:16:06Z
    reason: NoData
    status: Unknown
    type: Available
  - lastTransitionTime: 2019-06-05T18:16:06Z
    reason: NoData
    status: Unknown
    type: Upgradeable
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: infrastructures
  - group: config.openshift.io
    name: cluster
    resource: oauths
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-authentication
    resource: namespaces
  - group: ""
    name: authentication-operator
    resource: namespaces

$ oc get pods --all-namespaces | grep -i auth

> openshift-authentication-operator                       authentication-operator-6c9d7dc7b-zt8gx                           1/1       Running            1          12h
openshift-authentication                                oauth-openshift-7fc9c8bd5d-85wj6                                  1/1       Running            0          22m
openshift-authentication                                oauth-openshift-7fc9c8bd5d-hbtrj                                  1/1       Running            0          22m

$ oc logs authentication-operator-6c9d7dc7b-zt8gx -n openshift-authentication-operator

> I0606 06:41:51.169806       1 cmd.go:138] Using service-serving-cert provided certificates
I0606 06:41:51.171559       1 observer_polling.go:106] Starting file observer
I0606 06:41:52.688189       1 secure_serving.go:116] Serving securely on 0.0.0.0:8443
I0606 06:41:52.689646       1 leaderelection.go:205] attempting to acquire leader lease  openshift-authentication-operator/cluster-authentication-operator-lock...
I0606 06:42:57.489872       1 leaderelection.go:214] successfully acquired lease openshift-authentication-operator/cluster-authentication-operator-lock
I0606 06:42:57.491075       1 event.go:221] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"openshift-authentication-operator", Name:"cluster-authentication-operator-lock", UID:"fc7f90d4-87bd-11e9-a2a2-005056ab11e4", APIVersion:"v1", ResourceVersion:"195321", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' 2b3a6f30-8826-11e9-b86d-0a580a820031 became leader
I0606 06:42:57.493049       1 status_controller.go:183] Starting StatusSyncer-authentication
I0606 06:42:57.497202       1 controller.go:53] Starting AuthenticationOperator2
I0606 06:42:57.497367       1 resourcesync_controller.go:219] Starting ResourceSyncController
I0606 06:42:59.930408       1 event.go:221] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-authentication-operator", Name:"authentication-operator", UID:"20813df4-87bd-11e9-a3df-005056ab5877", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeploymentUpdated' Updated Deployment.apps/oauth-openshift -n openshift-authentication because it changed
E0606 06:42:59.967383       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:02.550516       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:05.130920       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:07.526528       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:09.920814       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:12.322594       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:14.722355       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:17.124281       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:19.533355       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:22.119572       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:24.523253       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:26.923203       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:31.702182       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:34.068468       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:43:37.594117       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:44:59.950581       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 06:47:44.230719       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
W0606 06:47:59.529700       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 195321 (197129)
E0606 06:48:01.170534       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
W0606 06:48:31.527213       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 195321 (197330)
W0606 06:48:42.516251       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 195321 (197408)
W0606 06:50:50.514268       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 195321 (198201)
E0606 06:53:12.347069       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
W0606 06:54:45.532230       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 197554 (199722)
W0606 06:55:32.536189       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 197356 (200010)
E0606 06:55:34.167676       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
W0606 06:56:50.550991       1 reflector.go:270] github.com/openshift/client-go/route/informers/externalversions/factory.go:101: watch of *v1.Route ended with: The resourceVersion for the provided watch is too old.
E0606 06:56:51.993818       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
W0606 06:57:00.519197       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 198432 (200558)
W0606 06:57:18.532695       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.Deployment ended with: too old resource version: 195622 (196329)
E0606 06:57:19.966126       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
W0606 06:58:00.523602       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 197621 (200966)
E0606 07:02:58.739133       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
E0606 07:03:01.141332       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
W0606 07:04:08.541948       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 200234 (203310)
E0606 07:04:10.178204       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: EOF
W0606 07:04:21.541270       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 199935 (203385)
W0606 07:04:38.524900       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 200799 (203498)
W0606 07:05:41.529327       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 201182 (203881)

**Comment by DanyC97** [comment]
@wilddeuces my 0.002$ suggestion will be to format the logs inserting inside md code, is easier for folks to take a look.

**Comment by enj** [comment]
Please reproduce using the 4.1 GA installer.

**Comment by wilddeuces** [comment]
> Please reproduce using the 4.1 GA installer.

I used the setup for vSphere instead of BareMetal and the newest Installer now and it worked flowlessly.
Thank you.
