### ISSUE TITLE
Authentication degraded v4.1 : failed to GET route: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by bjolivot** [openshift/cluster-authentication-operator#134]
I can't boostrap new cluster, tried 3 times, same results
The certificate used by authentication pods is not valid

*** openshift-install version
./openshift-install v4.1.0-201905212232-dirty
built from commit 71d8978039726046929729ad15302973e3da18ce
release image quay.io/openshift-release-dev/ocp-release@sha256:b8307ac0f3ec4ac86c3f3b52846425205022da52c16f56ec31cbe428501001d6

***  oc get nodes
oc get nodes
NAME           STATUS   ROLES    AGE    VERSION
okd-master-0   Ready    master   3h6m   v1.13.4+cb455d664
okd-master-1   Ready    master   3h6m   v1.13.4+cb455d664
okd-master-2   Ready    master   3h6m   v1.13.4+cb455d664
okd-worker-1   Ready    worker   3h6m   v1.13.4+cb455d664
okd-worker-2   Ready    worker   3h6m   v1.13.4+cb455d664
okd-worker-3   Ready    worker   3h6m   v1.13.4+cb455d664

*** oc get co
NAME                                 VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                                 Unknown     Unknown       True       9m52s
cloud-credential                     4.1.0     True        False         False      3h6m
cluster-autoscaler                   4.1.0     True        False         False      3h6m
console                              4.1.0     True        False         False      177m
dns                                  4.1.0     True        False         False      3h5m
image-registry                                 False       False         True       3h
ingress                              4.1.0     True        False         False      179m
kube-apiserver                       4.1.0     True        False         False      3h4m
kube-controller-manager              4.1.0     True        False         False      3h3m
kube-scheduler                       4.1.0     True        False         False      3h3m
machine-api                          4.1.0     True        False         False      3h6m
machine-config                       4.1.0     True        False         False      3h5m
marketplace                          4.1.0     True        False         False      3h
monitoring                           4.1.0     True        False         False      177m
network                              4.1.0     True        False         False      3h5m
node-tuning                          4.1.0     True        False         False      3h2m
openshift-apiserver                  4.1.0     True        False         False      3h2m
openshift-controller-manager         4.1.0     True        False         False      3h5m
openshift-samples                    4.1.0     True        False         False      174m
operator-lifecycle-manager           4.1.0     True        False         False      3h4m
operator-lifecycle-manager-catalog   4.1.0     True        False         False      3h4m
service-ca                           4.1.0     True        False         False      3h5m
service-catalog-apiserver            4.1.0     True        False         False      3h2m
service-catalog-controller-manager   4.1.0     True        False         False      3h2m
storage                              4.1.0     True        False         False      3h

*** oc get co authentication -oyaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  creationTimestamp: "2019-06-19T13:04:33Z"
  generation: 1
  name: authentication
  resourceVersion: "54550"
  selfLink: /apis/config.openshift.io/v1/clusteroperators/authentication
  uid: c890f7f2-9292-11e9-843e-3ad4e0cc66cb
spec: {}
status:
  conditions:
  - lastTransitionTime: "2019-06-19T13:04:33Z"
    message: 'Degraded: error checking current version: unable to check route health:
      failed to GET route: x509: certificate signed by unknown authority'
    reason: DegradedOperatorSyncLoopError
    status: "True"
    type: Degraded
  - lastTransitionTime: "2019-06-19T13:04:33Z"
    reason: NoData
    status: Unknown
    type: Progressing
  - lastTransitionTime: "2019-06-19T13:04:33Z"
    reason: NoData
    status: Unknown
    type: Available
  - lastTransitionTime: "2019-06-19T13:04:33Z"
    reason: NoData
    status: Unknown
    type: Upgradeable
  extension: null
  relatedObjects:
  - group: operator.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: authentications
  - group: config.openshift.io
    name: cluster
    resource: infrastructures
  - group: config.openshift.io
    name: cluster
    resource: oauths
  - group: ""
    name: openshift-config
    resource: namespaces
  - group: ""
    name: openshift-config-managed
    resource: namespaces
  - group: ""
    name: openshift-authentication
    resource: namespaces
  - group: ""
    name: authentication-operator
    resource: namespaces

*** oc get pods --all-namespaces | grep -i auth
openshift-authentication-operator                       authentication-operator-69d5d8bf84-6pdvq                          1/1     Running     0          11m
openshift-authentication                                oauth-openshift-6889dd56f6-6s6rx                                  1/1     Running     0          10m
openshift-authentication                                oauth-openshift-6889dd56f6-kgnmm                                  1/1     Running     0          10m

*** oc logs -n openshift-authentication-operator  authentication-operator-69d5d8bf84-6pdvq

W0619 13:11:14.297959       1 reflector.go:270] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: watch of *v1.Infrastructure ended with: too old resource version: 14653 (55932)
W0619 13:11:14.298005       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.Secret ended with: too old resource version: 54387 (55421)
W0619 13:11:14.298042       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.Secret ended with: too old resource version: 54520 (55421)
W0619 13:11:14.310693       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.Service ended with: too old resource version: 54487 (55422)
W0619 13:11:14.314416       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 54449 (56288)
W0619 13:11:14.314452       1 reflector.go:270] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: watch of *v1.Ingress ended with: too old resource version: 14655 (55932)
W0619 13:11:14.324679       1 reflector.go:270] k8s.io/client-go/informers/factory.go:132: watch of *v1.ConfigMap ended with: too old resource version: 54531 (56288)
W0619 13:11:14.341407       1 reflector.go:270] github.com/openshift/client-go/operator/informers/externalversions/factory.go:101: watch of *v1.Authentication ended with: too old resource version: 54575 (56420)
W0619 13:11:14.357583       1 reflector.go:270] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: watch of *v1.Authentication ended with: too old resource version: 14655 (56420)
W0619 13:11:14.440928       1 reflector.go:270] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: watch of *v1.Console ended with: too old resource version: 14655 (56422)
W0619 13:11:14.459253       1 reflector.go:270] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: watch of *v1.OAuth ended with: too old resource version: 14655 (56422)
E0619 13:11:18.097725       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: x509: certificate signed by unknown authority
E0619 13:11:20.501783       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: x509: certificate signed by unknown authority
E0619 13:15:55.724989       1 controller.go:129] {AuthenticationOperator2 AuthenticationOperator2} failed with: error checking current version: unable to check route health: failed to GET route: x509: certificate signed by unknown authority

**Comment by stlaz** [comment]
I see
```
openshift-install version
./openshift-install v4.1.0-201905212232-dirty
```
The official release was 2019-06-06 though, closing, whatever before was a devel version and crashes were to be expected, many things got fixed from back then.

Do try an official release, or the current installer, it's working.
