### ISSUE TITLE
things david doesn't like

### ISSUE THREAD

**Issue by deads2k** [openshift/cluster-authentication-operator#141]
1. https://github.com/openshift/cluster-authentication-operator/blob/master/pkg/operator2/configmap.go#L55-L59 .  route.spec isn't the same as route.status. 
 Your route hasn't been accepted yet, so the kube-apiserver could end up forwarding to an endpoint that isn't you!
2.  This configmap is an output, not an input.  Please make it a separate control loop to keep your main loop tight with logical dependencies.  Also, you don't want a rollout failure to disrupt keeping this outbound information correct.
https://github.com/openshift/cluster-authentication-operator/blob/04eedbb3751852155db618bfd6e9ffa27f836f74/pkg/operator2/operator.go#L321-L326
3. Use a different `FooDegraded` for each control loop and allow the status union to combine them.  It will make each condition write more obvious.
4. `handleAuthConfig` is outbound state.  Move into a different sync loop
5. your check functions are good, but they should each set different `FooDegraded` conditions.
6. `serviceCA, servingCert, err := c.handleServiceCA()` appears unnecessary. Directly depend on the key and the kubelet will properly put your pod into pending.
7. hard code the hardcoded values in your oauth config.  Service name for instance.  Flexibility that isn't flexible is really hard to read.
8. instead of passing a bunch of state through various handles, use your clients to lookup values.  You can make them caching if the load becomes too high.
9. `accessTokenInactivityTimeoutSeconds` appears to be a default.  why didn't you default it?
10. `handleOAuthConfig` appears to be an attempt at combining multiple different configobservers into a single loop.  You do logically own all these things, but configobservation (even a single value) distinct from the main loop will give you working generations and logicaly separation you're lacking here.
11. sync-ing of user config is driven outside the main loop of other operators to ensure that it always works regardless of the state of other rollouts.  Secrets must rotate without choice, the old values are invalid.
12. ensureBootstrappedOAuthClients looks completely distinct.
13. looks like availability may be worth separating like static pod operators that have complicated availability rules.

**Comment by enj** [comment]
100% agree with all above except:

>     1. https://github.com/openshift/cluster-authentication-operator/blob/master/pkg/operator2/configmap.go#L55-L59 .  route.spec isn't the same as route.status.
>        Your route hasn't been accepted yet, so the kube-apiserver could end up forwarding to an endpoint that isn't you!

We never use the route until it is accepted and we explicitly set the host value.  We also ignore any changes to that value - it is always `oauth-openshift.` `+` `ingress.spec.domain`.  We can make the code more clear, but there is no chance of forwarding traffic to the wrong place.

>     6. `serviceCA, servingCert, err := c.handleServiceCA()` appears unnecessary. Directly depend on the key and the kubelet will properly put your pod into pending.

That code only exists to force a rollout on service CA rotation.  Most of it could be moved to `manifests` and delegated to CVO though.

>     8. instead of passing a bunch of state through various handles, use your clients to lookup values.  You can make them caching if the load becomes too high.

I think this will naturally fallout as things are broken apart.  The passing of state is mostly a by product of the state being available in one giant sync loop.

>     9. `accessTokenInactivityTimeoutSeconds` appears to be a default.  why didn't you default it?

I do not understand exactly what you are saying.  Tokens have no inactivity timeout by default since we do not hate our users.

`accessTokenInactivityTimeoutSeconds` is actually dead code in the operator since the logic to honor it lives in KAS, and KAS-O has no config observer to wire it into the authenticator.

>     12. ensureBootstrappedOAuthClients looks completely distinct.

Standa was having a hard time writing his first controller so I asked him to do the minimal work in the main loop to unblock Sally.  But yeah, it needs to go.

**Comment by stlaz** [comment]
2019-12-10 update:
Still todo:
1. skip based on the above comment? :ok: 
2.move oauth-metada CM handling to a separate control loop
3. naturally each controller should have its own degraded messages, we only have two (about to be three) controllers, any new controller should stick by the rule of own degraded messages
4. separate control loop for authentication.config
5. this should now be fine :ok:
6. looks like this could be safely moved to manifests now
7. hard-code the values in bindata similarly to what OAS-o does in its workload controller
8. this should mostly be solved by 10., there might still be some fallout from the the original mono-loop
9. this would be a topic for a standalone feature
10. this is attempted in https://github.com/openshift/cluster-authentication-operator/pull/222
11. I wonder if this means just syncing the config outside the main sync loop, say in the resource syncer, or if that's something else. @deads2k is that it or did you have something else in mind?
12. yeah, this needs to be moved, I wanted to go with the framework used elsewhere in the operator in https://github.com/openshift/cluster-authentication-operator/pull/136 which means splitting this into two separate controllers, but never got to finish it
13. condition handling seems somewhat fine at the moment it would make sense to review it to see if it matches somewhat to OAS-o or KAS-o are doing

**Comment by stlaz** [comment]
We have a gdoc splitting the work among other team members (only viewable if from Red Hat, sorry, community, not enough sharing options :disappointed: ) - https://docs.google.com/document/d/1S1o_K9CqQIwqnwL76PZczOaUCtznaH1K7eBX9CE0FOE/edit?usp=sharing
