### ISSUE TITLE
failed to decode metadata: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by pashok2398** [openshift/cluster-authentication-operator#164]
Openshift 4.1.7
UPI: vSphere
ENV: 3 masrers 3 workers

I configure OpenID OAuth:

```
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    release.openshift.io/create-only: 'true'
  creationTimestamp: '2019-07-29T19:12:50Z'
  generation: 19
  name: cluster
  resourceVersion: '250219'
  selfLink: /apis/config.openshift.io/v1/oauths/cluster
  uid: dbce3f57-b234-11e9-ba76-005056a5829d
spec:
  identityProviders:
    - mappingMethod: claim
      name: ibm
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: *****
        clientSecret:
          name: openid-client-secret-9z8dr
        issuer: 'https://w3id.sso.ibm.com/isam'
      type: OpenID
```
Getting error from the operator:
```
Update is failing. Cluster operator authentication is reporting a failure: Degraded: failed to apply IDP ibm config: failed to decode metadata: invalid character '<' looking for beginning of value. View Cluster Operators for more details.
```
I see the same in the authentication-operator pod:
```
E0730 09:33:40.282106       1 oauth.go:69] failed to honor IDP v1.IdentityProvider{Name:"ibm", MappingMethod:"claim", IdentityProviderConfig:v1.IdentityProviderConfig{Type:"OpenID", BasicAuth:(*v1.BasicAuthIdentityProvider)(nil), GitHub:(*v1.GitHubIdentityProvider)(nil), GitLab:(*v1.GitLabIdentityProvider)(nil), Google:(*v1.GoogleIdentityProvider)(nil), HTPasswd:(*v1.HTPasswdIdentityProvider)(nil), Keystone:(*v1.KeystoneIdentityProvider)(nil), LDAP:(*v1.LDAPIdentityProvider)(nil), OpenID:(*v1.OpenIDIdentityProvider)(0xc42098ab00), RequestHeader:(*v1.RequestHeaderIdentityProvider)(nil)}}: failed to decode metadata: invalid character '<' looking for beginning of value
```

Am i missing something?
Thanks

**Comment by enj** [comment]
Your `issuer` is incorrect.  It needs to be the URL of the actual OIDC server.  You have it set to the human facing SSO portal.

**Comment by pashok2398** [comment]
@enj Thanks for the suggestion,
I found the problem, our `issuer` discovery endpoint is `issuer` + `/well-known/openid-configuration`, and the operator looking for `issuer` + /.well-known/openid-configuration` (https://github.com/openshift/cluster-authentication-operator/blob/7a385e712749728452e590d23e3414721078f90d/pkg/operator2/idp.go#L239).
1. Is there an option for make it changeable (env var or something).
2. I rebuild the image and with the change, can you please advise where i should change the image name?
Thanks!!!

**Comment by enj** [comment]
> @enj Thanks for the suggestion,
> I found the problem, our `issuer` discovery endpoint is `issuer` + `/well-known/openid-configuration`

There is no support for servers that do not comply with the OIDC spec.

> and the operator looking for `issuer` + `/.well-known/openid-configuration`
> 
> https://github.com/openshift/cluster-authentication-operator/blob/7a385e712749728452e590d23e3414721078f90d/pkg/operator2/idp.go#L239
> 
> .
> 1. Is there an option for make it changeable (env var or something).

No.

> 2. I rebuild the image with the change i made to line 239, can you please advise where i should change the image name?
> 3. I tried to proxy the url :) `https://name.domain.com` + `/.well-known/openid-configuration` > `issuer` + `/well-known/openid-configuration` and got `Authentication Error` with `oauth-openshift-xxx-xxxx` `pod` log:
> 
> ```
> 12 07:36:47.400873       1 secure_serving.go:136] Serving securely on 0.0.0.0:6443
> I0812 07:36:47.400945       1 serving.go:77] Starting DynamicLoader
> I0812 07:36:47.401249       1 clientca.go:58] Starting DynamicCA: /tmp/requestheader-client-ca-file498890988
> I0812 07:36:47.401370       1 clientca.go:58] Starting DynamicCA: /tmp/client-ca-file354410369
> I0812 07:36:55.007738       1 log.go:172] http: TLS handshake error from 10.128.0.1:54208: remote error: tls: unknown certificate
> I0812 07:36:55.018528       1 log.go:172] http: TLS handshake error from 10.128.0.1:54210: EOF
> E0812 07:37:25.409243       1 errorpage.go:26] AuthenticationError: error parsing token: invalid character '<' looking for beginning of value
> ```
> 
> Thanks!!!

Provide all of the URLs you are using as well as the well known output.  Your server seems to be returning HTML.  I suspect that it is not a real OIDC server.

**Comment by pashok2398** [comment]
@enj 
When i access the `issuer` i see this page:
```
{
	"introspection_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/introspect",
	"coverage_map_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/coverage_map",
	"issuer": "https://w3id.sso.ibm.com/isam",
	"authorization_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/authorize",
	"token_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/token",
	"jwks_uri": "https://w3id-ns.sso.ibm.com/keys/prod/w3id-prod.jwk",
	"response_types_supported": ["code", "token", "id_token token"],
	"subject_types_supported": ["public"],
	"id_token_signing_alg_values_supported": ["RS256"],
	"userinfo_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/userinfo",
	"registration_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/registration",
	"scopes_supported": ["openid"],
	"claims_supported": ["sub"],
	"response_modes_supported": ["query", "fragment", "form_post"],
	"grant_types_supported": ["authorization_code", "implicit", "refresh_token"],
	"token_endpoint_auth_methods_supported": ["client_secret_post"],
	"display_values_supported": ["page"],
	"claim_types_supported": ["normal"],
	"claims_parameter_supported": false,
	"request_parameter_supported": false,
	"request_uri_parameter_supported": false,
	"require_request_uri_registration": false,
	"check_session_iframe": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/check_session_iframe",
	"end_session_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/end_session"
}
```

**Comment by enj** [comment]
What is the exact URL that serves that JSON document?

**Comment by pashok2398** [comment]
The URL is:
`https://devops.haifa.ibm.com/.well-known/openid-configuration`
The issuer in the OAuth yaml is:
`issuer: 'https://devops.haifa.ibm.com'`

**Comment by enj** [comment]
It looks like the `userinfo_endpoint` is broken on your OIDC server (it returns HTML and not JSON).  Since that endpoint is optional, I suggest updating your reverse proxy to drop that key and instead return:

```json
{
	"introspection_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/introspect",
	"coverage_map_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/coverage_map",
	"issuer": "https://w3id.sso.ibm.com/isam",
	"authorization_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/authorize",
	"token_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/token",
	"jwks_uri": "https://w3id-ns.sso.ibm.com/keys/prod/w3id-prod.jwk",
	"response_types_supported": ["code", "token", "id_token token"],
	"subject_types_supported": ["public"],
	"id_token_signing_alg_values_supported": ["RS256"],
	"registration_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/registration",
	"scopes_supported": ["openid"],
	"claims_supported": ["sub"],
	"response_modes_supported": ["query", "fragment", "form_post"],
	"grant_types_supported": ["authorization_code", "implicit", "refresh_token"],
	"token_endpoint_auth_methods_supported": ["client_secret_post"],
	"display_values_supported": ["page"],
	"claim_types_supported": ["normal"],
	"claims_parameter_supported": false,
	"request_parameter_supported": false,
	"request_uri_parameter_supported": false,
	"require_request_uri_registration": false,
	"check_session_iframe": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/check_session_iframe",
	"end_session_endpoint": "https://w3id.sso.ibm.com/isam/oidc/endpoint/amapp-runtime-oidcidp/end_session"
}
```

**Comment by enj** [comment]
@pashok2398 please close this issue if the above worked.  You will want to reach out to your OIDC provider to fix the missing discovery endpoint and broken user info endpoint.
