### ISSUE TITLE
Login URL shown for token display is not configurable

### ISSUE THREAD

**Issue by adarshaj** [openshift/cluster-authentication-operator#335]
"Copy Login Command" currently restrict the api url to be one from the in-cluster configuration; however, it is absolutely possible to place a load balancer in front of master servers and have users interact with api via loadbalancer. The only way the users will discover is by going to "Copy Login Command", so I need a way to configure the api loginUrl displayed there. A user configurable configmap or env value would be a good way to expose it.

**Comment by adarshaj** [comment]
Interesting.. no team members interact with the community reported issues? may be the readme should be updated to reflect this information so that we don't have to waste our time trying to report issues... All the activity I see in the issue tracker is @openshift-bot complaining about inactivity and closing them.. its better that the issue tracker on this repo be removed instead..

**Comment by stlaz** [comment]
Sorry, trying to maintain quite a number of components causes my attention to revolve mostly around Bugzillas and RFEs from customers (which is a sad state, I know).

Even if you did put a loadbalancer in front of your cluster, authentication will still use the URLs that are behind your load balancer, so if you log in to the concole, you get redirected to non-load-balanced oauth-server, which will redirect you to non-load balanced console.

The ability to change the default URLs for some of the control plane components, including the oauth server and console, is being considered for future versions.
