### ISSUE TITLE
Impossible to update route - Error in route oauth-openshift - 503 Service Unavailable

### ISSUE THREAD

**Issue by jdcano-bpe** [openshift/cluster-authentication-operator#388]
Hello,

I am installing a new cluster OCP 4.6.1

``` 
[root@paas-dev masters]# oc version
Client Version: 4.6.1
Server Version: 4.6.1
Kubernetes Version: v1.19.0+d59ce34
```

So far, all the operators are fine and available (not degraded) except the Authentication and the Console. 

```
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.6.1     False       True          True       25h
cloud-credential                           4.6.1     True        False         False      4d10h
cluster-autoscaler                         4.6.1     True        False         False      4d5h
config-operator                            4.6.1     True        False         False      4d5h
console                                    4.6.1     False       True          True       34h
csi-snapshot-controller                    4.6.1     True        False         False      53m
dns                                        4.6.1     True        False         False      4d5h
etcd                                       4.6.1     True        False         False      4d5h
image-registry                             4.6.1     True        False         False      4d5h
ingress                                    4.6.1     True        False         False      4d4h
insights                                   4.6.1     True        False         False      4d5h
kube-apiserver                             4.6.1     True        False         False      4d5h
kube-controller-manager                    4.6.1     True        False         False      4d5h
kube-scheduler                             4.6.1     True        False         False      4d5h
kube-storage-version-migrator              4.6.1     True        False         False      4d4h
machine-api                                4.6.1     True        False         False      4d5h
machine-approver                           4.6.1     True        False         False      4d5h
machine-config                             4.6.1     True        False         False      3h49m
marketplace                                4.6.1     True        False         False      50m
monitoring                                 4.6.1     True        False         False      48m
network                                    4.6.1     True        False         False      4d5h
node-tuning                                4.6.1     True        False         False      4d5h
openshift-apiserver                        4.6.1     True        False         False      54m
openshift-controller-manager               4.6.1     True        False         False      4d5h
openshift-samples                          4.6.1     True        False         False      4d5h
operator-lifecycle-manager                 4.6.1     True        False         False      4d5h
operator-lifecycle-manager-catalog         4.6.1     True        False         False      4d5h
operator-lifecycle-manager-packageserver   4.6.1     True        False         False      48m
service-ca                                 4.6.1     True        False         False      4d5h
storage                                    4.6.1     True        False         False      4d5h
``` 

Checking in the **console** project, all pods are not running because they can not access to the OAUTH endpoint.
```
[root@gvapaas-dev-bastion1 install_07122020]# oc get pods
NAME                         READY   STATUS    RESTARTS   AGE
console-574b85c888-77j6q     0/1     Running   15         73m
console-64cd86cd6c-5wxzk     0/1     Running   15         73m
console-9bbf5899-pjdzf       0/1     Running   14         68m
downloads-85df645c7c-8nr7h   1/1     Running   0          2d3h
downloads-85df645c7c-n8jcq   1/1     Running   0          2d3h
```
The error comes because the **oauth-openshift** route is not properly working: 
```
2020-12-11T20:02:22Z auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.ocp-dev.mydomain.com/oauth/token failed: Head "https://oauth-openshift.apps.ocp-dev.mydomain.com": read tcp 10.129.0.17:46794->192.168.10.10:443: read: connection reset by peer
```

So I check the pods in the **openshift-authentication** and **openshift-authentication-projects** and all pods are running fine, but the one in the **openshift-authentication-projects** with an error:
```
[root@paas-dev masters]# oc get pods -n openshift-authentication
NAME                               READY   STATUS    RESTARTS   AGE
oauth-openshift-6dbc889fc8-96wbj   1/1     Running   0          55m
oauth-openshift-6dbc889fc8-mxhmp   1/1     Running   0          58m

[root@paas-dev masters]# oc get pods -n openshift-authentication-operator
NAME                                       READY   STATUS    RESTARTS   AGE
authentication-operator-5d575b6f8b-9q8jz   1/1     Running   0          55m
```
The error is the following:
```
E1211 19:47:18.497520       1 base_controller.go:250] "OAuthRouteCheckEndpointAccessibleController" controller failed to sync "key", err: "https://oauth-openshift.apps.ocp-dev.mydomain/healthz" returned "503 Service Unavailable"
``` 

Checking about this error, I found some information in Red Hat and it is related to certificates in the route, so everything make sense:
https://access.redhat.com/solutions/4601031

Then, the solution should be upgrade the route called **oauth-openshift**  in the project **openshift-authentication** to change the configuration to reencrypt the connection using the certificates from my load balancer in (apps.ocp-dev.mydomain.com). So, in order to do it properly, I follow the instructions to set up a certificate for all the subdomain **apps.** The instructions are here:

https://docs.openshift.com/container-platform/4.6/security/certificates/replacing-default-ingress-certificate.html

So far, this is working fine for all the routes, except for the one called **oauth-openshift**  in the project **openshift-authentication**. 

Next step is to try to modify this route by `oc edit route oauth-openshift`. So far, this is not possible and every time I try to change it, it comes to the default and original value. I tried creating a new route but then it happens the same and it is not possible to update the other projects with the new route even if I am cluster-admin.

This is the original value:
```
NAME                        HOST/PORT                                            PATH   SERVICES          PORT   TERMINATION            WILDCARD
oauth-openshift             oauth-openshift.apps.ocp-dev.corp.sch.ch                    oauth-openshift   6443   passthrough/Redirect   None
```

This is the desired output:
```
NAME                        HOST/PORT                                            PATH   SERVICES          PORT   TERMINATION            WILDCARD
oauth-openshift             oauth-openshift.apps.ocp-dev.corp.sch.ch                    oauth-openshift   6443   reencrypt/Redirect   None
```

So my question, **is there a way to update this route?** Is there something I am doing wrong? 

Thanks a lot in advance,
Best regards,

**Comment by stlaz** [comment]
> Checking about this error, I found some information in Red Hat and it is related to certificates in the route
503s do not mean a certificate problem, it might be a problem with the HAProxy configuration (*what kind of deployment is this? AWS, GCP, bare metal?*)

The solution you found is wrong, you can't change anything that's managed by an operator, including routes.

You should be able to find more information by inspecting the conditions that the authentication operator is posting, try inspecting them:
`oc get clusteroperator authentication -o yaml`

However, given that the pods appear to be running for a longer period of time, I don't think it's a problem with what the authentication operator does, it's more likely something involving ingress and HAProxy.

**Comment by jdcano-bpe** [comment]
Hello,

Thanks for your answer. Indeed looks like a problem with the HAproxy / Ingress configuration but I did not manage to solve it. So far we are in a WMWare cluster and we used the official documentation to deploy it.

But when the authentication operator tries to deploy we get the following error:

```
 - lastTransitionTime: "2020-12-29T16:13:43Z"
    message: |-
      RouterCertsDegraded: secret/v4-0-config-system-router-certs.spec.data[apps.ocp-dev.example.com] -n openshift-authentication: certificate could not validate route hostname oauth-openshift.apps.ocp-dev.example.com: x509: certificate is valid for router-internal-default.openshift-ingress.svc, router-internal-default.openshift-ingress.svc.cluster.local, not oauth-openshift.apps.ocp-dev.example.com
      OAuthRouteCheckEndpointAccessibleControllerDegraded: "https://oauth-openshift.apps.ocp-dev.example.com/healthz" returned "503 Service Unavailable"
    reason: OAuthRouteCheckEndpointAccessibleController_SyncError::RouterCerts_InvalidServerCertRouterCerts
    status: "True"
    type: Degraded
```

I updated the Ingress certificate to use an external one with a wildcard *.apps.ocp-dev.example.com, all the other routes are working fine (grafana, prometheus, etc). I recreated the authentication operator many times in order to use the right secret but it is not working.

Thanks a lot again.

Best regards

**Comment by stlaz** [comment]
The authentication operator is always going to use the `openshift-config-managed/router-certs` secret (it copies it to `openshift-authentication` NS) that is populated by the ingress-operator based on its configuration.

**Comment by jdcano-bpe** [comment]
Thanks a lot @stlaz, 

In my case,  the secret openshift-config-managed/router-certs contains a certificate created by our internal PKI. So far, all other routes (like the one for Grafana and Prometheus) are working fine but not the authentication one. 
I am discussing with Red Hat Openshift Support in order to solve this issue as well.

Thanks again.
Best regards,

**Comment by stlaz** [comment]
The authentication operator is making some more detailed checks than most of the other operators do in order to make sure the authentication stack is working.

I'll leave this one on the folks from support to figure out with you, I believe they will be able to help you.

All the best,
Standa
