### ISSUE TITLE
Cannot connect to LDAP servers with certificate with only CN

### ISSUE THREAD

**Issue by ibotty** [openshift/cluster-authentication-operator#389]
I get the following error after updating to OKD 4.6.0-0.okd-2020-12-12-135354.

```
E1215 13:41:23.520778       1 login.go:171] Error authenticating "tf" with provider "ldap": LDAP Result Code 200 "Network Error": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0                                                                           
```

It looks like https://github.com/golang/go/issues/39568 is the culprit.  It used to work before and I assume the new oauth-openshift deployment was compiled with newer go.

**Comment by stlaz** [comment]
Hello,
Indeed the oauth-server is compiled with the newer golang. You will need to fix your certificate.
