### ISSUE TITLE
Operator is not reporting a ClusterOperator resource

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/cluster-authentication-operator#67]
Expected:

```sh
# find an operator status for this operator
# the object should have a pointer to the namespaces for this operator in RelatedObjects
# to support must-gather tool for diagnostics
oc get clusteroperators
```

Actual:
No `ClusterOperator` status appears to be reported.
This prevents the ClusterVersionOperator from knowing if a payload is rolling out properly.
It also prevents telemetry from collecting information if the operator/operand is function.

/cc @ericavonb

**Comment by derekwaynecarr** [comment]
The cluster operator CR should also be in the manifest list per this example:

https://github.com/openshift/machine-api-operator/pull/200

**Comment by stlaz** [comment]
Related PR: https://github.com/openshift/cluster-authentication-operator/pull/36
